### PR TITLE
Convert entity relation name back to camel case before querying

### LINKED ISSUE #28: EntityMetadataNotFoundError on posting entity with relation
Hi,

I got an issue about using the library for entities with relations.

I have 2 entities:
```
@Entity()
export class Cable {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @ManyToOne(() => Armor)
    twistArmor: Armor;
}

@Entity()
export class Armor {
    @PrimaryGeneratedColumn()
    id: number;
}
```

When I was trying to add a new cable 
```
{
  "data": {
    "type": "cable",
    "attributes": {
      "name": "new one"
    },
    "relationships": {
      "twistArmor": {
        "data": {
          "type": "armor",
          "id": "1"
        }
      }
    }
  }
}
```

I got an error:
```
EntityMetadataNotFoundError: No metadata for "armor" was found.
```

As I see, all names are transformed using camelToKebab function, but when time comes to find relation data, name of repository aren't converted back.
https://github.com/klerick/nestjs-json-api/blob/daa9a9b87faedd65fbfa283e395584e4f6e188f0/libs/json-api-nestjs/src/lib/mixin/service/typeorm/utils/utils-methode.ts#L351

Could you help me solve this problem, please?
Thanks

### PR DESCRIPTION
**Pull request by too-soon**
Fixes #28.

Sometimes an entity would not be found while trying to `POST` a resource with its relationship.
Like mentioned in the issue, we need to convert our entity name back to camel case before querying.

### CODE REVIEW

**Comment by klerick** [comment]
@Mites-G thanks for contribute. Could you add unit test for this case?

**Comment by too-soon** [comment]
@klerick can you help me creating a new relationship on the mock database?

It needs to have an underline character(`_`) in its name to test my feature but I couldn't figure out how to do so.

Something to that effect:
```ts
  @OneToOne(() => Addresses, (item) => item.id)
  @IsNotEmpty()
  @JoinColumn({
    name: 'addresses_id',
  })
  public address_data: Addresses;
  ```

**Comment by klerick** [comment]
you shoukd create table using SQL in this [file](https://github.com/klerick/nestjs-json-api/blob/master/libs/json-api-nestjs/src/lib/mock-utils/db-for-test) 
and create entity for [test](https://github.com/klerick/nestjs-json-api/tree/master/libs/json-api-nestjs/src/lib/mock-utils/entities) and add reletion. and use it in test. I believe,  create separate entity will better solution for unit test which cover this case.

if you have problem, let me know, tomorro  I will have free time and will try to do it myself

**Comment by too-soon** [comment]
@klerick I managed to do it, thank you for helping out.

Here's the test before the fix:
image

And now after:
image

**Review by klerick — APPROVED** [review]

**Comment by klerick** [comment]
thank you!

**Pull request merged**
